config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

 	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	root 'home#index'
  	
	get 'signup' => 'users#new'
	get 'login' => 'sessions#new', as: :login
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'

  # PayPal payment processing
	post '/hook_sponsor' => 'tournaments#hook_sponsor'
	post '/hook_play' => 'tournaments#hook_play'

	resources :tournaments do 
	  member do
	  	get :players, :organizers, :sponsors
	  	post :member_out_of_group, :add_member, :create_group, :delete_group
	  end
	end

	resources :users do
		member do
			get :played_events, :organized_events, :sponsored_events
		end
	end
	
	resources :golf_courses
	post '/operate_golf_course' => 'golf_courses#operate_course'
	post '/not_operate_golf_course' => 'golf_courses#stop_operate'

	resources :join, only: [:create, :destroy]
	resources :tickets
	resources :requests, only: [:new, :create, :destroy]
	resources :golf_requests, only: [:new, :create, :destroy]
	resources :password_resets

	get "/pages/:page" => "pages#show"	
	#NOTE: this should appear at VERY end for not found pages
	get '*unmatched_route', to: 'home#not_found'
end

app/controllers/golf_courses_controller.rb
class GolfCoursesController < ApplicationController
	before_action :require_user, only: [:new, :create, :operate_course, :stop_operate]
	before_action :is_course_admin, only: [:edit, :update, :destroy]
	def index
		@golf_courses = GolfCourse.all
	end

	def show
		@golf_course = GolfCourse.find(params[:id])
		@is_admin = current_user && current_user.dealt_a_course?(@golf_course, 0)
		@is_manager = current_user && current_user.dealt_a_course?(@golf_course, 1)
		@hosted_tournaments = []
		Tournament.all.each do |t|
			if t.golf_course_id == @golf_course.id
				@hosted_tournaments << t
			end
		end

		@google_api_key = google_api_key
	end

	def edit
		@golf_course = GolfCourse.find(params[:id])
	end

	def update
		@golf_course = GolfCourse.find(params[:id])
		if @golf_course.update_attributes(golf_course_params)
            redirect_to(:action => 'show', :id => @golf_course.id)
        else
            render 'edit'
        end
	end

	def new
		@golf_course = GolfCourse.new
	end
	def create
		@golf_course = GolfCourse.new(golf_course_params)
		if current_user && @golf_course.save
			current_user.deal_course(@golf_course, 0)
			redirect_to golf_course_path(@golf_course)
		else
			render 'new'
		end
	end

	def destroy
		@golf_course = GolfCourse.find(params[:id])
		if @golf_course
			@golf_course.destroy
		end
		redirect_to golf_courses_path
	end

	#Admin & Manager
	def operate_course
		@golf_course = GolfCourse.find(params[:golf_course_id])
		@joinType = params[:join].to_i
		if !current_user.nil? && current_user.dealt_a_course?(@golf_course, 0) && @joinType==1
			current_user.deal_course(@golf_course, 1)
			redirect_to golf_course_path(@golf_course)
		elsif !current_user.nil? && !@joinType.nil? && @joinType >= 0 && @joinType <= 1
			if !current_user.dealt_a_course?(@golf_course, @joinType)
				redirect_to new_golf_request_path(selected_course: @golf_course.id, golf_request_type: @joinType)
				#current_user.deal_course(@golf_course, @joinType)
                #redirect_to golf_course_path(@golf_course)
			end
    	end
	end
	
	def stop_operate
		@golf_course = GolfCourse.find(params[:golf_course_id])
		@joinType = params[:join].to_i
		if !current_user.nil? && !@joinType.nil? && @joinType >= 0 && @joinType <= 1
			if current_user.dealt_a_course?(@golf_course, @joinType)
				current_user.not_deal_course(@golf_course, @joinType)
                redirect_to golf_course_path(@golf_course)
			end
    	end
	end

	private
	def golf_course_params
		params.require(:golf_course).permit(:name, :overview, :address, :website, :contact_info)
	end
	def is_course_admin
		return current_user && current_user.dealt_a_course?(@golf_course, 0)
	end
end

app/helpers/golf_courses_helper.rb
module GolfCoursesHelper
end

app/views/golf_courses/_form.html.erb
<!-- Don't use "form_for :tournament", that got routing problems  -->
<html>
<head>
	<link rel="stylesheet" type="text/css" href="css/style.css" />
</head>

<div id="tournament_div">
	<%= form_for(@golf_course) do |f| %>

      <div class="form-group row">
        <%= f.label :golf_course_name, :class=>"col-xs-3 col-form-label" %>
        <div class="col-xs-9">
          <%= f.text_field :name, :placeholder => "Golf Course Name", :class => "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :overview, :class=>"col-xs-3 col-form-label" %>
        <div class="col-xs-9">
          <%= f.text_field :overview, :placeholder => "Overview", :class => "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :address, :class=>"col-xs-3 col-form-label" %>
        <div class="col-xs-9">
          <%= f.text_field :address, :placeholder => "Address", :class => "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :contact_information, :class=>"col-xs-3 col-form-label" %>
        <div class="col-xs-9">
          <%= f.text_field :contact_info, :placeholder => "Contact Information", :class => "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :website, :class=>"col-xs-3 col-form-label" %>
        <div class="col-xs-9">
          <%= f.text_field :website, :placeholder => "Website", :class => "form-control" %>
        </div>
      </div>
       	 
   		<%= f.submit "Add Golf Course", :class => "button button_new btn" %>
  <% end %>
</div>
</html>

app/views/golf_courses/_show_requests.html.erb
<% if requests.any? %>
    <h3> <%= title %> </h3>
    <table class="table main-table">
      <% requests.each do |r| %>
        <% request_sender=User.find(r.sender_id) %>
        <% request_golf_course = GolfCourse.find(r.receiver_id) %>
          <tr>
            <td>
              <% if current_user == request_sender %>
                  You sent the organization request for
              <% else %>
                <%= link_to (request_sender.first_name + " " + request_sender.last_name), user_path(request_sender) %>
                (<%= link_to request_sender.email, user_path(request_sender) %>)
                wants to 
                <% if r.golf_request_type == 0 %>be admin for 
                <% else%>be CSR for 
                <% end %>
              <% end %>

              <%= link_to request_golf_course.name, golf_course_path(request_golf_course) %>:
              <i><%= r.message %></i>
            </td>
            
            <% if current_user.dealt_a_course?(request_golf_course, 0) %>
              <td><%= link_to 'Approve', golf_request_path(:id => r.id, :approval => 1, :is_golf_course => true), method: :delete, data: { :confirm => 'Confirm that you approve?' }, :class=>"button_new button btn-small"  %></td>
              <td><%= link_to 'Reject', golf_request_path(:id => r.id, :approval => 0, :is_golf_course => true), method: :delete, data: { :confirm => 'Confirm that you reject?' }, :class=>"button_new button btn-small"  %></td>
            <% end %>

          </tr>
      <% end %>
    </table>
<% end %>

app/views/golf_courses/edit.html.erb
<h1> Edit Golf Course </h1>
<%= render 'form' %>
<%= link_to 'Cancel Edit', "/golf_courses" %>

app/views/golf_courses/index.html.erb
<html>
<head>
  <title>GolfStuff - Golf Courses</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
</head>

<body>
    <div id="wrap">
    <%=render "header_menu"%>
    <%= image_tag("ball.jpg", :alt => "golf ball", :class => "img-banner") %>

      <div class="container">

        <h1>Current Golf Courses</h1>

          <table class="table main-table">
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th></th>
              </tr>
              <% @golf_courses.each do |g| %>
                <tr>
                    <td><%= g.id %></td>
                    <td><%= g.name %></td>
                    <td>
                      <%= link_to "Details", golf_course_path(g), :class=>"button button_new btn-table btn-sm" %>
                    </td>
                </tr>
              <% end %>
            </table>
            <%= link_to 'New Golf Course', "/golf_courses/new", :class => "button button_new btn" %>

      </div> <!--End of container-->

      <div id="push"></div>
    </div><!-- End of wrap -->

    <%= render "footer" %>

</body>
</html>

app/views/golf_courses/new.html.erb
<html>
<head>
  <title>GolfStuff - New Golf Course</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
</head>

<body>
<div id="wrap">
  <%=render "header_menu"%>

  <div class="container">

    <div class="col-sm-6 col-sm-offset-3">
      <h1>New Golf Course</h1>
			<%= render 'form' %>
			<%= link_to 'Cancel', "/golf_courses", :class => "button button_new_stop btn" %>
    </div>
  </div> <!--End of container-->
  <div id="push"></div>
</div><!-- End of wrap -->

<%= render "footer" %>

</body>
</html>

app/views/golf_courses/show.html.erb
<html>

<head>
  <title>Golf Stuff - Golf Course</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
</head>

<body>
  <div id="wrap">
    <%=render "header_menu"%>

    <div class="container">

      <h1 class="tournament-title"><%= @golf_course.name %></h1>

      <div class="container editing-link-box">
        <% if @is_admin || @is_manager %>
          <%= link_to 'Edit Golf Course Details', edit_golf_course_path(@golf_course), :class=>"btn-small button button_new"%>
        <% end %>
        <% if @is_admin %>
          <%= link_to 'Delete', golf_course_path(@golf_course), method: :delete, data: { confirm: 'You sure you want to delete this golf course?' }, :class=>"btn-small button button_new_stop" %>
        <% end %>
      </div>

      <div class="container">
      <table class="table-info">
        <tr>
          <th>Golf Course Name</th>
          <td><%= @golf_course.name %></td>
        </tr>
        <tr>
          <th>Overview</th>
          <td><%= @golf_course.overview %></td>
        </tr>
        <tr>
          <th>Address</th>
          <td><%= @golf_course.address %></td>
        </tr>
        <tr>
          <th>Contact Information</th>
          <td><%= @golf_course.contact_info %></td>
        </tr>
        <tr>
          <th>Website</th>
          <td><%= link_to @golf_course.website, @golf_course.website %></td>
        </tr>
        </table>
      </div>

        <!--<div><span>Golf Course Name:</span> <%= @golf_course.name %></div>-->
        <!--<div><span>Overview:</span> <%= @golf_course.overview %></div>-->
        <!--<div><span>Address:</span> <%= @golf_course.address %></div>-->
        <!--<div><span>Contact Information:</span> <%= @golf_course.contact_info %></div>-->
        <!--<div><span>Website:</span> <%= link_to @golf_course.website, @golf_course.website %></div>-->

        <div></div>
        <% if !@golf_course.nil? %>
          <iframe class="course-map" src="https://www.google.com/maps/embed/v1/place?key=<%= @google_api_key %>&q=+<%= @golf_course.name %>" allowfullscreen></iframe>
        <% end %>

      
      <!--Show requests-->
      <% if @is_admin%>
        <div class="requests-box">
          <%= render partial: "show_requests", locals: {title: "Pending Admin Requests for This Golf Course", requests: @golf_course.received_admin_requests, admin_req: true} %>
          <%= render partial: "show_requests", locals: {title: "Pending CSR Requests for This Golf Course", requests: @golf_course.received_csr_requests, admin_req: false} %>
        </div>
      <% end %>

      <i>To become CSR & Admin you need to send a request that may be approved/rejected by admins. However, if you are an admin for this golf course, no request message is needed</i>
      <div class="row">
        <div class="col-sm-6 text-center">
              <% if current_user.nil? || !current_user.dealt_a_course?(@golf_course, 0) %>
                <%= button_to "Become Admin", {:controller => "golf_courses", :action => "operate_course", :method=> :post, :params=> {golf_course_id: @golf_course.id, join: 0}}, {:class=>"button_new button"} %>
              <% else %>
                <%= button_to "Stop Admin", {:controller => "golf_courses", :action => "stop_operate", :method=> :post, :params=> {golf_course_id: @golf_course.id, join: 0}}, data: { confirm: 'Are you sure you want to stop administering this golf course?' }, :class=>"button_new_stop button" %>
              <% end %>
        </div>
        <div class="col-sm-6 text-center">
              <% if current_user.nil? || !current_user.dealt_a_course?(@golf_course, 1) %>
                <%= button_to "Become CSR", {:controller => "golf_courses", :action => "operate_course", :method=> :post, :params=> {golf_course_id: @golf_course.id, join: 1}}, {:class=>"button_new button"} %>
              <% else %>
                <%= button_to "Stop being CSR", {:controller => "golf_courses", :action => "stop_operate", :method=> :post, :params=> {golf_course_id: @golf_course.id, join: 1}}, data: { confirm: 'Are you sure you want to stop managing this golf course?' }, :class=>"button_new_stop button" %>
              <% end %>
        </div>
      </div>

        <!-- Admins & CSRs -->
        <h3>Golf Course Admins</h3>
        <div class="row tourn-btn-row">
            <%= render partial: "tournaments/show_persons_for_one_event", :locals => { :@title => nil, :@persons => @golf_course.admins, :@player_subgroup => false, :@is_player_group => false, :is_organizer => false} %>
        </div>

        <h3>Golf Course CSRs(Managers)</h3>
        <div class="row tourn-btn-row">
            <%= render partial: "tournaments/show_persons_for_one_event", :locals => { :@title => nil, :@persons => @golf_course.managers, :@player_subgroup => false, :@is_player_group => false, :is_organizer => false} %>
            <br>
        </div>

        <h3>Hosted Tournaments</h3>
        <div class="row tourn-btn-row">
            <%= render partial: "users/show_events_for_one_person", locals: { :@title => nil, :@events => @hosted_tournaments } %>
        </div>
        <%= render_shareable %>
    </div> <!--End of container-->
    
    <div id="push"></div>
  </div><!-- End of wrap -->

  <%= render "footer" %>

</body>
</html>