config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

 	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	root 'home#index'
  	
	get 'signup' => 'users#new'
	get 'login' => 'sessions#new', as: :login
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'

  # PayPal payment processing
	post '/hook_sponsor' => 'tournaments#hook_sponsor'
	post '/hook_play' => 'tournaments#hook_play'

	resources :tournaments do 
	  member do
	  	get :players, :organizers, :sponsors
	  	post :member_out_of_group, :add_member, :create_group, :delete_group
	  end
	end

	resources :users do
		member do
			get :played_events, :organized_events, :sponsored_events
		end
	end
	
	resources :golf_courses
	post '/operate_golf_course' => 'golf_courses#operate_course'
	post '/not_operate_golf_course' => 'golf_courses#stop_operate'

	resources :join, only: [:create, :destroy]
	resources :tickets
	resources :requests, only: [:new, :create, :destroy]
	resources :golf_requests, only: [:new, :create, :destroy]
	resources :password_resets

	get "/pages/:page" => "pages#show"	
	#NOTE: this should appear at VERY end for not found pages
	get '*unmatched_route', to: 'home#not_found'
end

app/models/user.rb
class User < ActiveRecord::Base
	#Personal info
	before_create { generate_token(:auth_token) }
	before_save { self.email = email.downcase }
	
	validates :first_name, presence: true, length: { maximum: 50 }
	validates :last_name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
		format: { with: VALID_EMAIL_REGEX, message: "Not appropriate e-mail address" },
		uniqueness: { case_sensitive: false }

	def get_user_name
		user_name = self.first_name + " " + self.last_name
		return user_name
	end

	#Profile Picture
	has_attached_file :profile_picture, :styles => {large: "600x600>", medium: "300x300>", thumb: "150x150#"}
	validates_attachment_content_type :profile_picture, content_type: /\Aimage\/.*\Z/\

	#Password
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, :on => :create

	#Tickets
	#This ticket model will saved all the tickets for this user
	#With tickets_type identify the type of tickets
	has_many :tickets
	has_many :tournaments, through: :tickets

	#========== Tournament Involvements ===============
	has_many :player_involvements, class_name: "Play", foreign_key: "person_id",
									dependent: :destroy
	has_many :played_events, through: :player_involvements, source: :event

	def send_password_reset
		generate_token(:password_reset_token)
		self.password_reset_sent_at = Time.zone.now
        	save!
		UserMailer.password_reset(self).deliver
	end

	def generate_token(column)
	begin
		self[column] = SecureRandom.urlsafe_base64
	end while User.exists?(column => self[column])
	end
	
	def send_confirmation
		
		UserMailer.confirmation(self).deliver
		end
		
	def play_in(some_event)
		if(!self.played_in?(some_event))
			player_involvements.create(event_id: some_event.id)
		end
	end
	def not_play(some_event)
		if(self.played_in?(some_event))
			player_involvements.find_by(event_id: some_event.id).destroy
		end
	end
	def played_in?(some_event)
		played_events.include?(some_event)
	end

	has_many :organizer_involvements, class_name: "Organize", foreign_key: "person_id",
									dependent: :destroy
	has_many :organized_events, through: :organizer_involvements, source: :event
	def organize_a(some_event)
		if(!self.organized_a?(some_event))
			organizer_involvements.create(event_id: some_event.id)
		end
	end
	def not_organize(some_event)
		if(self.organized_a?(some_event))
			organizer_involvements.find_by(event_id: some_event.id).destroy
		end
	end
	def organized_a?(some_event)
		organized_events.include?(some_event)
	end

	has_many :sponsor_involvements, class_name: "Sponsor", foreign_key: "person_id",
									dependent: :destroy
	has_many :sponsored_events, through: :sponsor_involvements, source: :event
	def sponsor_a(some_event)
		if(!self.sponsored_a?(some_event))
			sponsor_involvements.create(event_id: some_event.id)
		end
	end
	def not_sponsor(some_event)
		if(self.sponsored_a?(some_event))
			sponsor_involvements.find_by(event_id: some_event.id).destroy
		end
	end
	def sponsored_a?(some_event)
		sponsored_events.include?(some_event)
	end

	#Requests
	has_many :sent_requests, class_name: "Request", foreign_key: "sender_id",
			dependent: :destroy
	#has_many :wanted_events, through: :sent_requests, source: :receiver
	def received_requests
		@requests=[]
		organized_events.each do |e|
			e.received_requests.each do |new_request|
				@requests << new_request
			end
		end
		return @requests
  end

  #========== Golf Course Involvements ===============
  has_many :admin_course_rel, class_name: "CourseAdmin", foreign_key: "admin_id",
  								dependent: :destroy
  has_many :admined_courses, through: :admin_course_rel, source: :golf_course

  has_many :manage_course_rel, class_name: "CourseManager", foreign_key: "manager_id",
  								dependent: :destroy
  has_many :managed_courses, through: :manage_course_rel, source: :golf_course
  def deal_course(some_course, type)
  	if(!self.dealt_a_course?(some_course, type))
  		case type
  		when 0
  			admin_course_rel.create(golf_course_id: some_course.id)
  		when 1
  			manage_course_rel.create(golf_course_id: some_course.id)
  		end
  	end
  end
  def not_deal_course(some_course, type)
  	if(self.dealt_a_course?(some_course, type))
  		case type
	  	when 0
	  		admin_course_rel.find_by(golf_course_id: some_course.id).destroy
	  	when 1
	  		manage_course_rel.find_by(golf_course_id: some_course.id).destroy
	  	end
  	end
  end
  def dealt_a_course?(some_course, type)
  	case type
  	when 0
  		return admined_courses.include?(some_course)
  	when 1
  		return managed_courses.include?(some_course)
  	end
  end

  def received_golf_admin_requests
  	@requests=[]
		admined_courses.each do |ac|
		ac.received_admin_requests.each do |new_request|
			@requests << new_request
		end
	end
	return @requests
  end

  def received_golf_csr_requests
  	@requests=[]
		admined_courses.each do |ac|
		ac.received_csr_requests.each do |new_request|
			@requests << new_request
		end
	end
	return @requests
  end

  # draft method to redirect to PayPal payment
	def paypal_url(root, pay_type, amount, name, event_id)
		return_path = ''
		if (pay_type == 'play')
			return_path = "#{root}hook_play"
		elsif (pay_type == 'sponsor')
			return_path = "#{root}hook_sponsor"
		end

		values = {
			business: "csc444.toronto-merchant@gmail.com", #created an account on PayPal Developer and fake Sandbox email addresses
			cmd: "_xclick",
	    return: return_path,
	    rm: 2,
			amount: amount,
			item_name: "#{name} Tournament Ticket",
	    item_number: event_id,
	    currency_code: "CAD",
	    notify_url: return_path
		}
		"#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" + values.to_query
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	http_basic_authenticate_with name: "admin", password: "admin", only: [:index]
	before_action :is_user_profile, except: [:index, :new, :create, :show]
	before_action :require_user, only: [:index, :show]

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
  	end

  	def edit
  		@user = User.find(params[:id])
  	end

	def create
		@user = User.new(user_params)

		if @user.save
			@user.send_confirmation
			log_in(@user)
			redirect_to @user
		else
			render 'new'
		end
	end

	def update
  		@user = User.find(params[:id])
 
  		if @user.update(user_params)
    		redirect_to @user
  		else
    		render 'edit'
  		end
	end

	def destroy
  		@user = User.find(params[:id])
  		log_out(@user)
  		@user.destroy
 
  		redirect_to users_path
	end

	def played_events
		@title = "Played Tournaments"
		@person = User.find(params[:id])
		@events = @person.played_events#.paginate(page: params[:page])
		render "_show_events_for_one_person"
	end

	def organized_events
		@title = "Organized Tournaments"
		@person = User.find(params[:id])
		@events = @person.organized_events#.paginate(page: params[:page])
		render "_show_events_for_one_person"
	end

	def sponsored_events
		@title = "Sponsored Tournaments"
		@person = User.find(params[:id])
		@events = @person.sponsored_events#.paginate(page: params[:page])
		render "_show_events_for_one_person"
	end

	private
		def user_params
			params.require(:user).permit(:first_name, :last_name, :gender, :date_of_birth, :phone_number, :address, :email, :password, :password_confirmation, :profile_picture)
		end
		def is_user_profile
			@user = User.find(params[:id])
			if !current_user || @user.id!=session[:user_id]
				redirect_to "/"
				return false
			else
				return true
			end
		end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.erb
<div class="col-sm-6 col-sm-offset-3">
  <%= form_for @user, :html => { :multipart => true } do |f| %>



      <div class="form-group row">
        <%= f.label :first_name, :class=>"col-xs-3 col-form-label" %>
        <div class="col-xs-9">
          <%= f.text_field :first_name, :placeholder => "First Name", :class =>"form-control",:required => true%>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :last_name, :class=>"col-xs-3 col-form-label" %>
        <div class="col-xs-9">
          <%= f.text_field :last_name, :placeholder => "Last Name", :class =>"form-control", :required => true%>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :profile_picture, :class=>"col-xs-3 col-form-label" %>
        <div class="col-xs-9">
          <%= f.file_field :profile_picture, :class => "form-control-file" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :phone_number, :class=>"col-xs-3 col-form-label" %>
        <div class="col-xs-9">
          <%= f.telephone_field :phone_number, :placeholder => "Phone Number", :class =>"form-control", :required => true%>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :address, :class=>"col-xs-3 col-form-label" %>
        <div class="col-xs-9">
         <%= f.text_field :address, :placeholder => "Address", :class =>"form-control", :required => true%>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :password, :class=>"col-xs-3 col-form-label" %>
        <div class="col-xs-9">
          <%= f.password_field :password, :placeholder => "at least 6 characters", :class =>"form-control", :required => false, :minlength => 6 %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :confirm_password, :class=>"col-xs-3 col-form-label" %>
        <div class="col-xs-9">
          <%= f.password_field :password_confirmation,:class =>"form-control", :required => false %>
        </div>
      </div>

    <%= f.submit "Submit", :class => "button button_new"%>

    <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li id="errors"><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

<% end %> <!-- End of form-->
</div>

app/views/users/_form.html.erb
<div class="col-sm-6 col-sm-offset-3">
  <%= form_for @user, :html => { :multipart => true } do |f| %>



      <div class="form-group row">
        <%= f.label :first_name, :class=>"col-xs-3 col-form-label" %>
        <div class="col-xs-9">
          <%= f.text_field :first_name, :placeholder => "First Name", :class =>"form-control",:required => true%>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :last_name, :class=>"col-xs-3 col-form-label" %>
        <div class="col-xs-9">
          <%= f.text_field :last_name, :placeholder => "Last Name", :class =>"form-control", :required => true%>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :profile_picture, :class=>"col-xs-3 col-form-label" %>
        <div class="col-xs-9">
          <%= f.file_field :profile_picture, :class => "form-control-file" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :gender, :class=>"col-xs-3 col-form-label" %>
        <div class="col-xs-9">
          <%= f.text_field :gender, :placeholder => "Male/Female/Prefer not to say", :class => "form-control", :required => false%>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :date_of_birth, :class=>"col-xs-3 col-form-label" %>
        <div class="col-xs-9">
          <%= f.date_select :date_of_birth, start_year: 1900, :required => true, :class => "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :email, :class=>"col-xs-3 col-form-label" %>
        <div class="col-xs-9">
          <%= f.email_field :email, :placeholder => "Email", :class =>"form-control", :required => true%>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :phone_number, :class=>"col-xs-3 col-form-label" %>
        <div class="col-xs-9">
          <%= f.telephone_field :phone_number, :placeholder => "Phone Number", :class =>"form-control", :required => true%>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :address, :class=>"col-xs-3 col-form-label" %>
        <div class="col-xs-9">
         <%= f.text_field :address, :placeholder => "Address", :class =>"form-control", :required => true%>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :password, :class=>"col-xs-3 col-form-label" %>
        <div class="col-xs-9">
          <%= f.password_field :password, :placeholder => "at least 6 characters", :class =>"form-control", :required => true, :minlength => 6 %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :confirm_password, :class=>"col-xs-3 col-form-label" %>
        <div class="col-xs-9">
          <%= f.password_field :password_confirmation,:class =>"form-control", :required => true%>
        </div>
      </div>

    <%= f.submit "Submit", :class => "button button_new"%>

    <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li id="errors"><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

<% end %> <!-- End of form-->
</div>

app/views/users/_show_courses_for_one_person.html.erb
<h2><%= @title %></h2>

<% if @golf_courses && @golf_courses.any? %>
  <table class="table main-table">
    <tr>
      <th>Golf Course ID</th>
      <th>Golf Course Name</th>
      <th></th>
    </tr>
    <% @golf_courses.each do |g| %>
      <tr>
        <td><%= g.id %></td>
        <td><%= g.name %></td>
        <td><%= link_to "Show Details", golf_course_path(g),  :class=>"btn-small btn-table button_new button" %></td>
      </tr>
      <% end %>
  </table>
<% elsif @golf_courses%>
  None
<% end %>

app/views/users/_show_events_for_one_person.html.erb
<% if @title %>
  <h2><%= @title %></h2>
<% end %>

<% if @events && @events.any? %>
  <table class="table main-table">
    <tr>
      <th>Tournament ID</th>
      <th>Tournament Name</th>
      <th></th>
    </tr>
    <% @events.each do |e| %>
      <tr>
        <td><%= e.id %></td>
        <td><%= e.name %></td>
        <td><%= link_to "Show Details", tournament_path(e),  :class=>"btn-small btn-table button_new button" %></td>
      </tr>
      <% end %>
  </table>
<% elsif @events%>
  <div class="none-info">None</div>
<% end %>

app/views/users/edit.html.erb
<%=render "header_menu"%>
	<div class="col-sm-6 col-sm-offset-3">
		<h1>Edit user</h1>
	</div>
 
<%= render 'edit_form' %>

app/views/users/index.html.erb
<html>
<head>
  <title>Golf Stuff - All Users</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
</head>

<body>
<div id="wrap">
  <%=render "header_menu"%>
  <%= image_tag("ball.jpg", :alt => "golf ball", :class => "img-banner") %>

  <div class="container">

    <h1>All Users</h1>
    <div class="tourn-btn-row">
      <%= link_to 'New user', new_user_path, class: "button button_new btn btn-add" %>
    </div>

    <table class="table main-table">
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= link_to 'Show', user_path(user),  class: "button button_new btn-table" %></td>
          <td><%= link_to 'Edit', edit_user_path(user), class: "button button_new btn-table" %></td>
          <td>
            <%= link_to 'Destroy', user_path(user),
            method: :delete,
            data: { confirm: 'Are you sure?' },
            class: "button button_new_stop btn-table" %>
          </td>
        </tr>
      <% end %>
    </table>

  </div> <!--End of container-->

  <div id="push"></div>
</div><!-- End of wrap -->

<%= render "footer" %>

</body>
</html>

app/views/users/new.html.erb
<html>

<head>
  <title>Golf Stuff - Sign Up</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
</head>

<body>
  <div id="wrap">
    <%=render "header_menu"%>
    <div class="container">
      <div class="col-sm-6 col-sm-offset-3">
        <h1>Sign Up</h1>
      </div>
        <%= render "form"%>
    </div> <!--End of container-->

    <div id="push"></div>
  </div><!-- End of wrap -->

  <%= render "footer" %>

</body>
</html>

app/views/users/show.html.erb
<html>

<head>
  <title>Golf Stuff - Login</title>
</head>

<body>
  <div id="wrap">
    <%=render "header_menu"%>

    <div class="container">

      <div class="row">
        <h1 class="tournament-title"><%= @user.first_name %> <%= @user.last_name %></h1>
      </div>

      <% if current_user == @user %>

        <h2>Welcome to your personal profile, <%= @user.first_name %></h2>

        <div class="requests-box">
          <%= render partial: "tournaments/show_requests", locals: {title: "Sent Tournament Organization Requests", requests: @user.sent_requests} %>
          <%= render partial: "tournaments/show_requests", locals: {title: "Received Tournament Organization Requests", requests: @user.received_requests} %>
          <%= render partial: "golf_courses/show_requests", locals: {title: "Received Golf Course Admin Requests", requests: @user.received_golf_admin_requests} %>
          <%= render partial: "golf_courses/show_requests", locals: {title: "Received Golf Course CSR Requests", requests: @user.received_golf_csr_requests} %>
        </div>
      
      <% else %>

        <h2>Profile page for <%= @user.first_name %> <%= @user.last_name %></h2>

      <% end %>

      <div class="row">
        <div class="col-xs-8">
          <table class="table table-info">
            <tr>
              <th>First Name</th>
              <td><%= @user.first_name %></td>
            </tr>
            <tr>
              <th>Last Name</th>
              <td><%= @user.last_name %></td>
            </tr>
            <tr>
              <th>Gender</th>
              <td><%= @user.gender %></td>
            </tr>
            <tr>
              <th>Birthdate</th>
              <td><%= @user.date_of_birth %></td>
            </tr>
          </table>

          <h4>Contact Information</h4>
          <table class="table table-info">
            <tr>
              <th>Email</th>
              <td><%= @user.email %></td>
            </tr>
            <tr>
              <th>Phone Number</th>
              <td><%= @user.phone_number %></td>
            </tr>
            <tr>
              <th>Address</th>
              <td><%= @user.address %></td>
            </tr>
          </table>
        </div>
        <div class="col-xs-4">
          <!--<%= image_tag("avatar.png", :alt => "golf ball", :class => "avatar")%> -->
          <% if @user.profile_picture.file? %>
            <%= image_tag @user.profile_picture.url(:medium) %>
          <% else %>
            <%= image_tag("avatar.png", :alt => "golf ball", :class => "avatar")%>
          <% end %> 
        </div>
      </div>

      <%= render partial: "show_events_for_one_person", locals: { :@title => "Organized Tournaments", :@events => @user.organized_events } %>

      <%= render partial: "show_events_for_one_person", locals: { :@title => "Played Tournaments", :@events => @user.played_events } %>

      <%= render partial: "show_events_for_one_person", locals: { :@title => "Sponsored Tournaments", :@events => @user.sponsored_events } %>
      <br>
      <%= render partial: "show_courses_for_one_person", locals: { :@title => "Administered Golf Courses", :@golf_courses => @user.admined_courses } %>
      <%= render partial: "show_courses_for_one_person", locals: { :@title => "Managed Golf Courses (run CSR for)", :@golf_courses => @user.managed_courses } %>
      <br>
      <br>
      <% if current_user == @user %>
        <%= link_to 'Edit My Profile', edit_user_path(@user), :class => "button_new button col-sm-4 col-sm-offset-4"%>
      <% end %>

    </div><!-- End of container -->
    <div id="push"></div>
  </div><!-- End of wrap -->

  <%= render "footer" %>

</body>
</html>