config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

 	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	root 'home#index'
  	
	get 'signup' => 'users#new'
	get 'login' => 'sessions#new', as: :login
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'

  # PayPal payment processing
	post '/hook_sponsor' => 'tournaments#hook_sponsor'
	post '/hook_play' => 'tournaments#hook_play'

	resources :tournaments do 
	  member do
	  	get :players, :organizers, :sponsors
	  	post :member_out_of_group, :add_member, :create_group, :delete_group
	  end
	end

	resources :users do
		member do
			get :played_events, :organized_events, :sponsored_events
		end
	end
	
	resources :golf_courses
	post '/operate_golf_course' => 'golf_courses#operate_course'
	post '/not_operate_golf_course' => 'golf_courses#stop_operate'

	resources :join, only: [:create, :destroy]
	resources :tickets
	resources :requests, only: [:new, :create, :destroy]
	resources :golf_requests, only: [:new, :create, :destroy]
	resources :password_resets

	get "/pages/:page" => "pages#show"	
	#NOTE: this should appear at VERY end for not found pages
	get '*unmatched_route', to: 'home#not_found'
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
	#Players/Organizers/Sponsors Roles
	validates :name, presence: true, length: { maximum: 50 }
	validates :description, length: {maximum: 300}
	#Tickets
	has_many :tickets
	has_many :user, through: :tickets

	has_many :player_attendings, class_name: "Play", foreign_key: "event_id",
									dependent: :destroy
	has_many :players, through: :player_attendings, source: :person
	def got_player?(some_player)
		players.include?(some_player)
	end


	has_many :organizer_attendings, class_name: "Organize", foreign_key: "event_id"
	has_many :organizers, through: :organizer_attendings, source: :person
	def got_organizer?(some_organizer)
		organizers.include?(some_organizer)
	end

	has_many :sponsor_attendings, class_name: "Sponsor", foreign_key: "event_id"
	has_many :sponsors, through: :sponsor_attendings, source: :person
	def got_sponsor?(some_sponsor)
		sponsors.include?(some_sponsor)
	end

	#Request
	has_many :received_requests, class_name: "Request", foreign_key: "receiver_id",
			dependent: :destroy

	#Player groups
	has_many :player_groups, class_name: "Playergroup", foreign_key: "tournament_id"
	def new_group
		pg = player_groups.create(tournament_id: self.id)
		return pg
	end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
    before_action :require_user, only: [:new, :create]
    before_action :private_permission, only: [:show]
    before_action :require_organizer, only: [:edit, :update, :destroy]
    protect_from_forgery except: [:hook_sponsor, :hook_play]

    def index
        @tournaments = Tournament.all
    end

    def show
        @tournament = Tournament.find(params[:id])
        @is_organizer = current_user && current_user.organized_a?(@tournament)
        @unassigned_players = []
        @unassigned_dump = []
        @group_of_groups = []
        @group_id = []
        if @tournament.players.any?
            @tournament.players.each do |p|
                @unassigned_players << p
            end
            @tournament.player_groups.each do |pg|
                @players_in_group = []
                @group_id << pg.id
                pg.group_members.each do |usr_id|
                    @user= User.find(usr_id)
                    @players_in_group << @user
                    @unassigned_players = @unassigned_players.reject do |p|
                        p==@user
                    end
                end
                @group_of_groups << { id: pg.id, players: @players_in_group }
            end
            @unassigned_players.each do |p|
                @unassigned_dump << [p.id.to_s+". "+p.first_name+" "+p.last_name+"("+p.email+")", p.id]
            end
        end #end if

        if !@tournament.golf_course_id.nil?
            @golf_course = GolfCourse.find(@tournament.golf_course_id)
        end

        @google_api_key = google_api_key
    end

    def edit
        @tournament = Tournament.find(params[:id])
    end

    def update
        @tournament = Tournament.find(params[:id])
        if @tournament.update_attributes(tournament_params)
            redirect_to(:action => 'show', :id => @tournament.id)
        else
            render 'edit'
        end
    end

    def new
        @tournament = Tournament.new
        @organizer = current_user
        @organizer.organize_a(@tournament)
    end
    
    def create
        @tournament=Tournament.new(tournament_params)
        @curr_user = current_user
        if !@curr_user.nil? && @tournament.save
            @curr_user.organize_a(@tournament)
            redirect_to tournament_path(@tournament) #may change later '/tournaments'
        else
            render 'new'
        end
    end

    def destroy
        @tournament = Tournament.find(params[:id])
        if !@tournament.nil?
            @tournament.destroy
        end
        redirect_to tournaments_path
    end

    def create_group
        if !params[:id].nil? && !params[:id].empty?
            @tournament = Tournament.find(params[:id])
            if !@tournament.nil? && current_user && current_user.organized_a?(@tournament)
                Playergroup.create(tournament_id: @tournament.id)
                redirect_to tournament_path(@tournament)
            end
        end
    end

    def delete_group
        if !params[:group_id].nil? && !params[:group_id].empty? && !params[:id].nil? && !params[:id].empty?
            @tournament = Tournament.find(params[:id])
            if !@tournament.nil? && current_user && current_user.organized_a?(@tournament)
                @pg = Playergroup.find(params[:group_id])
                @pg.destroy
                redirect_to tournament_path(@tournament)
            end
        end
    end

    def add_member
        if !params[:tournament_id].nil? && !params[:tournament_id].empty? && !params[:group_id].nil? && !params[:group_id].empty? && !params[:added_member].nil? && !params[:added_member].empty?
            @tournament = Tournament.find(params[:id])
            @group = Playergroup.find(params[:group_id])
            @member = User.find(params[:added_member])
            if !@tournament.nil? && !@group.nil? && !@member.nil?
                if current_user && current_user.organized_a?(@tournament)
                    @group.add_member(@member)
                    @group.save
                end
                redirect_to tournament_path(@tournament)
            end
        end
    end

    def member_out_of_group
        @member = User.find(params[:member])
        @tournament = Tournament.find(params[:id])
        if !@member.nil? && !@tournament.nil? && current_user && current_user.organized_a?(@tournament)
            @tournament.player_groups.each do |pg|
                if pg.has_member?(@member)
                    pg.remove_member(@member)
                    pg.save
                    if pg.num_members == 0
                        pg.destroy
                    end
                end
            end
            redirect_to tournament_path(@tournament)
        end
    end


    def players
        @title = "Players"
        @event = Tournament.find(params[:id])
        @persons = @event.players#.paginate(page: params[:page])
        render "_show_persons_for_one_event"
    end

    def organizers
        @title = "Organizers"
        @event = Tournament.find(params[:id])
        @persons = @event.organizers#.paginate(page: params[:page])
        render "_show_persons_for_one_event"
    end

    def sponsors
        @title = "Sponsors"
        @event = Tournament.find(params[:id])
        @persons = @event.sponsors#.paginate(page: params[:page])
        render "_show_persons_for_one_event"
    end
    
    def hook_sponsor
      params.permit! # Permit all Paypal input params
      status = params[:payment_status]
      if status == "Completed"
        @tournament = Tournament.find(params[:item_number])
        current_user.sponsor_a(@tournament)
        redirect_to(:action => 'show', :id => @tournament.id)
      else
        render nothing: true
      end
    end

    def hook_play
      params.permit! # Permit all Paypal input params
      status = params[:payment_status]
      amount = params[:mc_gross]
      if status == "Completed"
        @tournament = Tournament.find(params[:item_number])
        current_user.play_in(@tournament)
        if amount == @tournament.price
            @ticket = Ticket.create(user_id: current_user.id, tournament_id: @tournament.id, tickets_type: 'Play')
        else
            @ticket = Ticket.create(user_id: current_user.id, tournament_id: @tournament.id, tickets_type: 'Play & Eat')
        end
        redirect_to controller: "tickets", action: "show", id: @ticket.id
      else
        render nothing: true
      end
    end
    
    private
    def tournament_params
        params.require(:tournament).permit(:name, :id, :location, :date, :contact_email, :contact_name, :description, :is_private, :golf_course_id, :price)
    end

    def private_permission
        @tournament = Tournament.find(params[:id])
        if @tournament && @tournament.is_private!=0
            if current_user
                return true
            else
                redirect_to '/'
            end
        end
    end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.erb
<%= form_for @tournament, :html => { :multipart => true } do |t| %>

    <div class="form-group row">
       <%= t.label :tournament_name, :class=>"col-xs-3 col-form-label" %>
      <div class="col-xs-9">
        <%= t.text_field :name, :placeholder => "Tournament Name", :class =>"form-control",:required => true%>
      </div>
    </div>

    <div class="form-group row">
      <%= t.label :private_tournament?, :class=>"col-xs-3 col-form-label" %>
      <div class="col-xs-9">
        <%= t.select :is_private, options_for_select([['Public', 0], ['Private', 1]], @tournament.is_private), {}, {:class=>"form-control", :include_blank => false} %>
        <small class="text-muted form-text">Private tournaments will not show up on the "tournaments" page. Outsiders(not logged in) will not be able to view private tournaments.</small>
      </div>
    </div>

      <div class="form-group row">
        <%= t.label :price, :class=>"col-xs-3 col-form-label" %>
        <div class="col-xs-9">
          <%= t.text_field :price, :placeholder => "Price", :class => "form-control", :pattern => "\\d*" %>
        </div>
      </div>

    <div class="form-group row">
      <%= t.label :location, :class=>"col-xs-3 col-form-label" %>
      <div class="col-xs-9">
        <% @golf_course_dump = [] %>
      <% (GolfCourse.all).each do |gf| %>
          <% @golf_course_dump << [gf.id.to_s+". "+gf.name+"("+gf.address+")", gf.id] %>
      <% end %>
      <% if !@golf_course_dump.empty? %>
        <%= t.select :golf_course_id, options_for_select(@golf_course_dump), {:include_blank => true}, {:class=>"form-control"} %>
        <small class="form-text text-muted">Note: If both fields are filled in, the location field, though recorded, will be covered with the address of the selected golf course</small>
        <small class="form-text text-muted">Select an existing golf course in the list</small>

      <% else %>
        <div class="none-info">No registered golf courses available now...</div>
      <% end %>


        <div class="form-group row">
          <% if !@golf_course_dump.empty? %>
            <label class="col-xs-4 col-form-label">Or enter a location</label>
          <% else %>
            <label class="col-xs-4 col-form-label">Enter a location</label>
          <% end %>
          <div class="col-xs-8">
            <%= t.text_field :location, :placeholder => "Location", :class => "form-control" %>
          </div>
        </div>
      </div>
    </div>

    <div class="form-group row">
      <%= t.label :date, :class=>"col-xs-3 col-form-label" %>
      <div class="col-xs-9">
        <%= t.datetime_select :date, start_year: Date.current.year, :class => "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <%= t.label :email, :class=>"col-xs-3 col-form-label" %>
      <div class="col-xs-9">
        <%= t.text_field :contact_email, :placeholder => "Email", :class => "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <%= t.label :contact_name, :class=>"col-xs-3 col-form-label" %>
      <div class="col-xs-9">
        <%= t.text_field :contact_name, :placeholder => "Name", :class => "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <%= t.label :description, :class=>"col-xs-3 col-form-label" %>
      <div class="col-xs-9">
        <%= t.text_area :description, cols: "58", rows: "10", :maxlength => 500, :placeholder => "Type your tournament description here...", :class => "form-control"%>
      </div>
    </div>

    <div class="block-center">
      <%= t.submit "Create Tournament", :class => "button button_new btn" %>
      <%= link_to 'Cancel', "/tournaments", :class => "button button_new_stop btn" %>
  </div>
<% end %> <!-- End of form-->

app/views/tournaments/_show_persons_for_one_event.html.erb
<% if !@player_subgroup %>
  <% if @title %>
    <h2><%= @title %></h2>
  <% end %>
<% end %>
<% if @persons && @persons.any? %>
  <table class="table main-table">
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th></th>
      <% if @is_player_group && @is_organizer %>
        <th></th>
      <% end %>
    </tr>
  	<% @persons.each do |p| %>
      <tr>
        <td><%= p.first_name %></td>
        <td><%= p.last_name %></td>
        <td><%= p.email %></td>
        <td><%= link_to 'Show Profile', user_path(p), :class=>"btn btn-sm button_new button btn-table" %></td>
        <% if @is_player_group && @is_organizer%>
          <td><%= link_to 'Remove user from group', member_out_of_group_tournament_path(member: p), method: :post, class: "button_new_stop button btn btn-sm"%></td>
        <% end %>
      </tr>
    <% end %>
  </table>
<% elsif @persons %>
  <% if @is_player_group %>
    <div class="none-info">No members</div>
  <% else %>
    <div class="none-info">None</div>
  <% end %>
<% end %>

app/views/tournaments/_show_requests.html.erb
<% if requests.any? %>
    <h3> <%= title %> </h3>
    <table class="table main-table">
      <% requests.each do |r| %>
        <% request_sender=User.find(r.sender_id) %>
        <% request_tournament = Tournament.find(r.receiver_id) %>
          <tr>
            <td>
              <% if current_user == request_sender %>
                  You sent the organization request for
              <% else %>
                <%= link_to (request_sender.first_name + " " + request_sender.last_name), user_path(request_sender) %>
                (<%= link_to request_sender.email, user_path(request_sender) %>)
                wants to organize
              <% end %>

              <%= link_to request_tournament.name, tournament_path(request_tournament) %>:
              <i><%= r.message %></i>
            </td>

            <% if current_user.organized_a?(request_tournament) %>
              <td><%= link_to 'Approve', request_path(:id => r.id, :approval => 1, :is_golf_course => false), method: :delete, data: { :confirm => 'Confirm that you approve?' }, :class=>"button_new button btn-small"  %></td>
              <td><%= link_to 'Reject', request_path(:id => r.id, :approval => 0, :is_golf_course => false), method: :delete, data: { :confirm => 'Confirm that you reject?' }, :class=>"button_new button btn-small"  %></td>
            <% end %>

          </tr>
      <% end %>
    </table>
<% end %>

app/views/tournaments/edit.html.erb
<html>
<head>
  <title>GolfStuff - New Tournament</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
</head>

<body>
<div id="wrap">
  <%=render "header_menu"%>

  <div class="container">

    <div class="col-sm-6 col-sm-offset-3">
      <h1>Edit a torunament Tournament</h1>

      <%= render 'form' %>

    </div>
  </div> <!--End of container-->
  <div id="push"></div>
</div><!-- End of wrap -->

<%= render "footer" %>

</body>
</html>

app/views/tournaments/index.html.erb
<html>
<head>
  <title>Golf Stuff - Tournaments</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
</head>

<body>
  <div id="wrap">
      <%=render "header_menu"%>
      <%= image_tag("ball.jpg", :alt => "golf ball", :class => "img-banner") %>

      <div class="container">

          <h1>Tournaments</h1>

            <table class="table main-table">
                <tr>
                  <th>ID</th>
                  <th>Name</th>
                  <th>Location</th>
                  <th>Date</th>
                  <th>Actions</th>
                  <th></th>
                  <th></th>
                </tr>
                <% @tournaments.each do |t| %>
                <% if t.is_private == 0 %>
                  <tr>
                      <td><%= t.id %></td>
                      <td><%= t.name %></td>
                      <% if !t.golf_course_id.nil?%>
                        <% @gf = GolfCourse.find(t.golf_course_id)%>
                        <td><%= @gf.name %></td>
                      <% else %>
                        <td><%= t.location %></td>
                      <% end %>
                      <td><%= t.date %></td>
                      <td>
                        <%= link_to "Details", tournament_path(t), :class=>"btn btn-sm button button_new" %>
                      </td>
                      <td>
                        <% if current_user.nil? || !current_user.played_in?(t) %>
                            <%= link_to "PLAY!", {:controller => "tickets", :action => "new", :params => {:event_id => t.id}, :method=> :get}, {:class=>"btn btn-sm button button_new"} %>
                        <% else %>
                            <button type="button" class="btn btn-sm button button_new_stop" data-toggle="modal" data-target="#myModal">Stop Playing</button>

                          <div class="modal fade" id="myModal" role="dialog">
                            <div class="modal-dialog">
                              <!-- Modal content-->
                              <div class="modal-content">
                                <div class="modal-header">
                                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                                  <h4 class="modal-title">Are you sure you want to stop playing?</h4>
                                </div>
                                <div class="modal-footer">
                                <div class="form-inline">  
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                <%= link_to "Stop playing", join_path(:id => t.id, :params => {:event_id => t.id, :join => 0}), :method=> :delete, :class=>"btn btn-primary" %>
                                </div>
                                </div>
                              </div>
                            </div>
                          </div>

                        <% end %>
                      </td>
                  </tr>
                <% end %>
                <% end %>
            </table>

            <%= link_to 'New Tournament', "/tournaments/new", :class => "btn button button_new" %>

      </div> <!--End of container-->

      <div id="push"></div>
    </div><!-- End of wrap -->

    <%= render "footer" %>

</body>
</html>

app/views/tournaments/new.html.erb
<html>
<head>
  <title>GolfStuff - New Tournament</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
</head>

<body>
  <div id="wrap">
    <%=render "header_menu"%>

    <div class="container">

		  <div class="col-sm-6 col-sm-offset-3">
        <h1>New Tournament</h1>

			  <%= render 'form' %>

      </div>
    </div> <!--End of container-->
    <div id="push"></div>
  </div><!-- End of wrap -->

  <%= render "footer" %>

</body>
</html>

app/views/tournaments/show.html.erb
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>GolfStuff - Tournament</title>
</head>

<body>
  <div id="wrap">
    <%=render "header_menu"%>

    <div class="container">

      <h1 class="tournament-title"><%= @tournament.name %></h1>

      

      <!--Show Details-->
      <div class="container">
        <table class="table-info">
          <tr>
            <th>Permission</th>
            <% if @tournament.is_private!=0 %>
              <td><i>Private</i></td>
            <% else %>
              <td><i>Public</i></td>
            <% end %>
          </tr>
          <tr>
            <th>Date & Time</th>
            <% if !@tournament.date.nil? %>
              <td><%= @tournament.date %></td>
            <% else %>
              <td>N/A</td>
            <% end %>
          </tr>
          <tr>
            <th>Golf Course</th>
            <% if !@golf_course.nil?%>
              <td><%= link_to @golf_course.name, golf_course_path(@golf_course) %></td>
            <% else %>
              <td> N/A</td>
            <% end %>
          </tr>
          <tr>
            <th>Location</th>
            <% if !@golf_course.nil?%>
              <td><%= @golf_course.address %></td>
            <% elsif !@tournament.location.nil? && !@tournament.location.empty?%>
              <td><%= @tournament.location %></td>
            <% else %>
              <td>N/A</td>
            <% end %>
          </tr>
          <tr>
            <th>Price</th>
            <% if !@tournament.price.nil? %>
              <td><%= @tournament.price %> CAD</td>
            <% else %>
              <td>N/A</td>
            <% end %>
          </tr>
          <tr>
            <th>Contact Email</th>
            <% if !@tournament.contact_email.nil? && !@tournament.contact_email.empty? %>
              <td><%= @tournament.contact_email %></td>
            <% else %>
              <td>N/A</td>
            <% end %>
          </tr>
          <tr>
            <th>Contact Name</th>
            <% if !@tournament.contact_name.nil? && !@tournament.contact_name.empty? %>
              <td><%= @tournament.contact_name %></td>
            <% else %>
              <td>N/A</td>
            <% end %>
          </tr>
          <tr>
            <th>Description</th>
            <%if @tournament.description.nil? || @tournament.description.empty? %>
              <td>None</td>
            <% else %>
              <td><%= @tournament.description %></td>
            <% end %>
          </tr>
        </table>
      </div>
      <% if @is_organizer%>
            <div class="row editing-link-box">
                 <div class="col-sm-3">
                   <%= link_to 'Edit Details', edit_tournament_path(@tournament), :class=>"btn-small button button_new"%>
                 </div>
                 <div class="col-sm-3">
                      <button type="button" class="btn-small button button_new_stop" data-toggle="modal" data-target="#myModaldel">Delete Tournament</button>
                 </div>
            </div>
                <div class="modal fade" id="myModaldel" role="dialog">
                  <div class="modal-dialog">
                    <!-- Modal content-->
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Are you sure you want to delete this tournament?</h4>
                      </div>
                      <div class="modal-footer">
                      <div class="form-inline">  
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                      <%= link_to 'Delete Tournament', tournament_path(@tournament), method: :delete, :class=>"btn btn-primary"  %>
                      </div>
                      </div>
                    </div>
                  </div>
                </div>
      <% end %>

      <% if !@golf_course.nil? %>
        <iframe class="course-map" src="https://www.google.com/maps/embed/v1/place?key=<%= @google_api_key %>&q=+<%= @golf_course.name %>" allowfullscreen></iframe>
      <% else %>
        <iframe class="course-map" src="https://www.google.com/maps/embed/v1/place?key=<%= @google_api_key %>&q=+<%= @tournament.location %>" allowfullscreen></iframe>
      <% end %>
      <!--Show requests-->
      <% if @is_organizer%>
        <div class="requests-box">
          <%= render partial: "show_requests", locals: {title: "Pending Requests for This Tournament", requests: @tournament.received_requests} %>
        </div>
      <% end %>

      <!--Play/Sponsor/Organize options-->
        <div class="row tourn-btn-row">

          <div class="col-sm-4 text-center">
            <% if current_user.nil? || !current_user.played_in?(@tournament) %>
                <%= link_to "PLAY!", {:controller => "tickets", :action => "new", :params => {:event_id => @tournament.id}, :method=> :get}, {:class=>"btn btn-lg button_new button btn-long"} %>
            <% else %>
              <!-- Trigger the modal with a button -->
              <button type="button" class="btn btn-lg button_new_stop button btn-long" data-toggle="modal" data-target="#myModalply">Stop Playing</button>
                <div class="modal fade" id="myModalply" role="dialog">
                  <div class="modal-dialog">
                    <!-- Modal content-->
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Are you sure you want to stop playing?</h4>
                      </div>
                      <div class="modal-footer">
                      <div class="form-inline">  
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                      <%= link_to "Stop playing", join_path(:params => {:event_id => @tournament.id, :join => 0}), :method=> :delete, :class=>"btn btn-primary" %>
                      </div>
                      </div>
                    </div>
                  </div>
                </div>
            <% end %>
          </div>

          <div class="col-sm-4 text-center">
            <% if current_user.nil? || !current_user.organized_a?(@tournament) %>
                <%= button_to "Request to Organize", {:controller => "join", :action => "create", :method=> :post, :params=> {event_id: @tournament.id, join: 1}}, {:class=>"btn btn-lg button_new button btn-long"} %>
            <% else %>
                <button type="button" class="btn btn-lg button_new_stop button btn-long" data-toggle="modal" data-target="#myModalorg">Stop Organizing</button>
                <div class="modal fade" id="myModalorg" role="dialog">
                  <div class="modal-dialog">
                    <!-- Modal content-->
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Are you sure you want to stop organizing?</h4>

                      </div>
                      <div class="modal-footer">
                      <div class="form-inline">  
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                      <%= link_to "Stop organizing", join_path(:params => {:event_id => @tournament.id, :join => 1}), :method=> :delete, :class=>"btn btn-primary" %>
                      </div>
                      </div>
                    </div>
                  </div>
                </div>
                
            <% end %>
          </div>

          <div class="col-sm-4 text-center">
              <%= form_tag({:controller=> "join", :action => "create", :params=> {event_id: @tournament.id, join: 2, name: @tournament.name}}) do %>
                  <div class="input-group input-group-lg">
                    <div class="input-group-addon green-add-on">CAD</div>
                    <%= text_field_tag :sponsor_amount, nil, placeholder: "Donation amount", class: "form-control", :pattern => "\\d*.+\\d+\\d+" %>
                    <span class="input-group-btn">
                      <%= submit_tag "Sponsor", :class=>"btn btn-sponsor" %>
                    </span>
                  </div>
              <% end %>
          </div>

        </div>
      <!--End of Play/Organize/Sponsor Section-->

      <h2>Players</h2>
      <% if @is_organizer %>
          <%= button_to "Create Group", {:controller => "tournaments", :action => "create_group"}, {:class => "button_new button"} %>
      <% end %>
      <p class="text-muted">Note: Only organizers can put players into groups. In golf games, there can be at most 4 members in every group.</p>


      <% if @tournament.players.any? %>

          <!--Players with group-->
          <% i=0%>
          <% @group_of_groups.each do |pg| %>
              <b><i><%= "Player Group (ID #{@group_id[i]})" %></i></b>
              <% if !current_user.nil? && @is_organizer %>
                  <%= button_to "Delete Group", :controller => "tournaments", :action => "delete_group", :params => {:group_id => pg[:id]}, :class => "button_new_stop button" %>
              <% end %>

              <%= render partial: "show_persons_for_one_event", :locals => { :@title => "Player Group (ID #{@group_id[i]})", :@persons => pg[:players], :@player_subgroup => true, :@is_player_group => true} %>

              <% if pg[:players].length<4 && @is_organizer && !@unassigned_players.empty? %>
                  <%= form_tag :controller => "tournaments", :action => "add_member", :params => {:group_id => pg[:id], :tournament_id => @tournament.id}  do %>
                      <%= select_tag :added_member, options_for_select(@unassigned_dump), :prompt => "<select a player to add to group>", :include_blank => false %>
                      <%= submit_tag "Add Member to Group" %>
                  <% end %>
              <% elsif pg[:players].length==4 && @is_organizer %>
                  <i>4 members in group already (group <%=@group_id[i]%> is full)</i><br><br>
              <% end %>
              <% i+=1 %>
          <% end %>

          <!--Show players without group-->
          <% if !@unassigned_players.empty? %>
              <hr />
              <b><i><%= "Players without group" %></i></b>
              <%= render partial: "show_persons_for_one_event", :locals => { :@title => "Players without Group", :@persons => @unassigned_players, :@player_subgroup => true, :@is_player_group => false, :is_organizer => @is_organizer} %>
          <% end %>
      <% else %>
          <div>No players</div>
      <% end %>

      <%= render partial: "show_persons_for_one_event", :locals => { :@title => "Organizers", :@persons => @tournament.organizers, :@player_subgroup => false, :@is_player_group => false, :is_organizer => @is_organizer} %>

      <%= render partial: "show_persons_for_one_event", :locals => { :@title => "Sponsors", :@persons => @tournament.sponsors, :@player_subgroup => false, :@is_player_group => false, :is_organizer => @is_organizer} %>

      <!-- Social media sharing -->
      <%= render_shareable %>
    </div> <!--End of container-->

    <div id="push"></div>
  </div><!-- End of wrap -->

  <%= render "footer" %>
</body>
</html>